### ISSUE TITLE
full dynamic tracing failure for V8

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1035]
I tested to trace current V8 master with full dynamic tracing, but failed as follows:
```
$ uftrace record -P. ./d8 --expose-gc --trace-gc -e 'gc()'
dynamic: /home/honggyu/work/uftrace/arch/x86_64/mcount-dynamic.c:126:mcount_cleanup_trampoline
 ERROR: cannot restore trampoline due to protection: Invalid argument
```
I bisected the commits and found the problem from the following one.
- 1147486 dynamic: support libraries for dynamic tracing

It cannot simply be reverted right now, so need to take care of the problem later.

**Comment by honggyukim** [comment]
@ParkHanbum Please take a look if possible.

**Comment by honggyukim** [comment]
You can download the following binaries to reproduce the problem.
- [d8.txt](https://github.com/namhyung/uftrace/files/3853618/d8.txt)
- [snapshot_blob.bin.txt](https://github.com/namhyung/uftrace/files/3853619/snapshot_blob.bin.txt)

Then, try to run it if it works fine.
```
$ mv d8.txt d8
$ mv snapshot_blob.bin.txt snapshot_blob.bin

$ ./d8 -e 'console.log("Hello")'
Hello
```

**Comment by AnsBal** [comment]
Hello @honggyukim, I think the problem is the that the address is not aligned to the page size.

This patch should solve the problem:

```diff
diff --git a/arch/x86_64/mcount-dynamic.c b/arch/x86_64/mcount-dynamic.c
index 96912682..03737d2b 100644
--- a/arch/x86_64/mcount-dynamic.c
+++ b/arch/x86_64/mcount-dynamic.c
@@ -122,7 +122,9 @@ int mcount_setup_trampoline(struct mcount_dynamic_info *mdi)
 
 void mcount_cleanup_trampoline(struct mcount_dynamic_info *mdi)
 {
-       if (mprotect((void *)mdi->text_addr, mdi->text_size, PROT_EXEC))
+       void* text_addr = (void *)(mdi->text_addr & ~(getpagesize() - 1));
+
+       if (mprotect(text_addr, mdi->text_size, PROT_EXEC))
                pr_err("cannot restore trampoline due to protection");
 }
 
```

**Comment by honggyukim** [comment]
Hello @AnsBal,

Thanks very much for your effort, but it doesn't actually fix the problem. Here is the execution log.
```
$ uftrace record -P. --no-libcall -v ./d8 -e ''
uftrace: checking binary ./d8
uftrace: removing uftrace.data.old directory
uftrace: using /home/honggyu/usr/lib/libmcount.so library for tracing
uftrace: creating 10 thread(s) for recording
mcount: initializing mcount library
dynamic: dynamic patch type: d8: 0 (none)
dynamic: cannot setup trampoline due to protection: Invalid argument
dynamic: patched all (0) functions in 'd8'
mcount: mcount setup done
mcount: mcount trace finished
mcount: exit from libmcount
uftrace: child terminated with exit code: 0
uftrace: cannot find build-id section

$ uftrace replay
WARN: cannot open record data: uftrace.data: No data available
```

**Comment by AnsBal** [comment]
Ohh it seems that this patch had the be applied in another location in the code.

This fixed it for me:

```diff
diff --git a/arch/x86_64/mcount-dynamic.c b/arch/x86_64/mcount-dynamic.c
index d339c5a3..6edc4d2a 100644
--- a/arch/x86_64/mcount-dynamic.c
+++ b/arch/x86_64/mcount-dynamic.c
@@ -12,6 +12,7 @@
 #include "utils/symbol.h"
 
 #define PAGE_SIZE  4096
+#define PAGE_ADDR(a)    ((void *)((a) & ~(PAGE_SIZE - 1)))
 #define XRAY_SECT  "xray_instr_map"
 #define MCOUNTLOC_SECT  "__mcount_loc"
 
@@ -84,7 +85,7 @@ int mcount_setup_trampoline(struct mcount_dynamic_info *mdi)
                        pr_err("failed to mmap trampoline for setup");
        }
 
-       if (mprotect((void *)mdi->text_addr, mdi->text_size,
+       if (mprotect(PAGE_ADDR(mdi->text_addr), mdi->text_size,
                     PROT_READ | PROT_WRITE | PROT_EXEC)) {
                pr_dbg("cannot setup trampoline due to protection: %m\n");
                return -1;
@@ -122,7 +123,7 @@ int mcount_setup_trampoline(struct mcount_dynamic_info *mdi)
 

 void mcount_cleanup_trampoline(struct mcount_dynamic_info *mdi)
 {
-       if (mprotect((void *)mdi->text_addr, mdi->text_size, PROT_EXEC))
+       if (mprotect(PAGE_ADDR(mdi->text_addr), mdi->text_size, PROT_EXEC))
                pr_err("cannot restore trampoline due to protection");
 }
```

**Comment by honggyukim** [comment]
Thanks @AnsBal, it actually fixes a simple problem.
```
$ uftrace record -P. --no-libcall ./d8 -e ''
```
But doesn't fix the following problem.
```
$ uftrace record -P. --no-libcall ./d8 --expose-gc --trace-gc -e 'gc()'


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7fff2f30d070
==== C stack trace ===============================

    /home/honggyu/usr/lib/libmcount.so(backtrace+0x47) [0x7f3197434e87]
    ./d8(v8::base::debug::StackTrace::StackTrace()+0x13) [0x5646928ac9d3]
    ./d8(+0x123efcd) [0x5646928abfcd]
    ./d8(V8_Fatal(char const*, ...)+0x150) [0x5646928a64f0]
    ./d8(+0x8b495f) [0x564691f2195f]
    ./d8(v8::internal::InnerPointerToCodeCache::GetCacheEntry(unsigned long)+0xde) [0x564691eb587e]
    ./d8(v8::internal::StackFrame::ComputeType(v8::internal::StackFrameIteratorBase const*, v8::internal::StackFrame::State*)+0x11f) [0x564691eb44ff]
    ./d8(v8::internal::StackFrameIterator::Advance()+0x36) [0x564691eb3196]
    ./d8(+0x8516fd) [0x564691ebe6fd]
    ./d8(v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>)+0x68) [0x564691ebeeb8]
    ./d8(v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection)+0xca) [0x564691ed0bba]
    ./d8(v8::internal::ErrorUtils::MakeGenericError(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode)+0x166) [0x564691ed0e86]
    ./d8(v8::internal::Factory::NewError(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>)+0xa5) [0x564691ef4145]
    ./d8(v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, bool)+0x4e2) [0x564691fbba82]
    ./d8(v8::internal::Runtime_LoadNoFeedbackIC_Miss(int, unsigned long*, v8::internal::Isolate*)+0x122) [0x564691fc4922]
    ./d8(+0x114ead9) [0x5646927bbad9]
Received signal 4 ILL_ILLOPN 5646928a9e42
WARN: child terminated by signal: 4: Illegal instruction
```

**Comment by namhyung** [comment]
@AnsBal Yes the patch above would fix the problem given the description of the mprotect():

```
ERRORS
       EACCES The  memory  cannot be given the specified access.  This can happen,
              for example, if you mmap(2) a file to which you have read-only access,
              then ask mprotect() to mark it PROT_WRITE.

       EINVAL addr is not a valid pointer, or not a multiple of the system page size.

       EINVAL (pkey_mprotect()) pkey has not been allocated with pkey_alloc(2)

       EINVAL Both PROT_GROWSUP and PROT_GROWSDOWN were specified in prot.

       EINVAL Invalid flags specified in prot.
```

@honggyukim That's a different issue and reminds me of the days in node.js debugging... oh...

**Comment by ParkHanbum** [comment]
@honggyukim check that the functions which have 'Builtins_' prefix has recorded. these functions must be exclude from tracing list.

**Comment by honggyukim** [comment]
@ParkHanbum If so, is there any way to detect such functions?

**Comment by honggyukim** [comment]
> @AnsBal Yes the patch above would fix the problem given the description of the mprotect()

@AnsBal If so, could you send a PR for it?

**Comment by ParkHanbum** [comment]
you can use objdump to find functions or use python script replay.py

**Comment by honggyukim** [comment]
>> @ParkHanbum If so, is there any way to detect such functions?

> you can use objdump to find functions or use python script replay.py

I mean if such functions make the crash, then uftrace has to automatically detect and exclude those functions. We cannot ask users to run `objdump` to find and manually exclude the functions.

**Comment by AnsBal** [comment]
> Thanks @AnsBal, it actually fixes a simple problem.
> 
> ```
> $ uftrace record -P. --no-libcall ./d8 -e ''
> ```
> 
> But doesn't fix the following problem.
> 
> ```
> $ uftrace record -P. --no-libcall ./d8 --expose-gc --trace-gc -e 'gc()'
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0x7fff2f30d070
> ==== C stack trace ===============================
> 
>     /home/honggyu/usr/lib/libmcount.so(backtrace+0x47) [0x7f3197434e87]
>     ./d8(v8::base::debug::StackTrace::StackTrace()+0x13) [0x5646928ac9d3]
>     ./d8(+0x123efcd) [0x5646928abfcd]
>     ./d8(V8_Fatal(char const*, ...)+0x150) [0x5646928a64f0]
>     ./d8(+0x8b495f) [0x564691f2195f]
>     ./d8(v8::internal::InnerPointerToCodeCache::GetCacheEntry(unsigned long)+0xde) [0x564691eb587e]
>     ./d8(v8::internal::StackFrame::ComputeType(v8::internal::StackFrameIteratorBase const*, v8::internal::StackFrame::State*)+0x11f) [0x564691eb44ff]
>     ./d8(v8::internal::StackFrameIterator::Advance()+0x36) [0x564691eb3196]
>     ./d8(+0x8516fd) [0x564691ebe6fd]
>     ./d8(v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>)+0x68) [0x564691ebeeb8]
>     ./d8(v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection)+0xca) [0x564691ed0bba]
>     ./d8(v8::internal::ErrorUtils::MakeGenericError(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode)+0x166) [0x564691ed0e86]
>     ./d8(v8::internal::Factory::NewError(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>)+0xa5) [0x564691ef4145]
>     ./d8(v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, bool)+0x4e2) [0x564691fbba82]
>     ./d8(v8::internal::Runtime_LoadNoFeedbackIC_Miss(int, unsigned long*, v8::internal::Isolate*)+0x122) [0x564691fc4922]
>     ./d8(+0x114ead9) [0x5646927bbad9]
> Received signal 4 ILL_ILLOPN 5646928a9e42
> WARN: child terminated by signal: 4: Illegal instruction
> ```

Ii investigated the problem and found that when main is not patched (using -N main) the problem disappear:

 ``` 
$ uftrace record  -P. -N main --no-libcall /home/anas/Downloads/d8 --expose-gc --trace-gc -e 'gc()'
[17671:0x555557073150]        9 ms: Mark-sweep 0.3 (1.6) -> 0.3 (2.6) MB, 1.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested  
```
This is the asm dump of main (Notice the jump instead of ret):
 ``` 
gdb -batch -ex 'file /home/anas/Downloads/d8' -ex 'disassemble/rs main'
Dump of assembler code for function main:
   0x00000000006ef140 <+0>:	55	push   %rbp
   0x00000000006ef141 <+1>:	48 89 e5	mov    %rsp,%rbp
   0x00000000006ef144 <+4>:	5d	pop    %rbp
   0x00000000006ef145 <+5>:	e9 f6 ec ff ff	jmpq   0x6ede40 <_ZN2v85Shell4MainEiPPc>
End of assembler dump.
```

**Comment by honggyukim** [comment]
> Ii investigated the problem and found that when main is not patched (using -N main) the problem disappear:

If you intended to "unpatch" `main` function, you can use `-U main`. Please read the description in the man page for `-U`/`--unpatch` option for more details.

**Comment by honggyukim** [comment]
It still shows the problem if I use `-U main`. It seems that the return hooking makes the problem in some specific function.
```
$ uftrace record  -P. -U main --no-libcall ./d8 --expose-gc --trace-gc -e 'gc()'


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7fff6ee60480
==== C stack trace ===============================

    /home/honggyu/usr/lib/libmcount.so(backtrace+0x47) [0x7f5919406027]
    ./d8(v8::base::debug::StackTrace::StackTrace()+0x13) [0x55df1843f9d3]
    ./d8(+0x123efcd) [0x55df1843efcd]
    ./d8(V8_Fatal(char const*, ...)+0x150) [0x55df184394f0]
    ./d8(+0x8b495f) [0x55df17ab495f]
    ./d8(v8::internal::InnerPointerToCodeCache::GetCacheEntry(unsigned long)+0xde) [0x55df17a4887e]
    ./d8(v8::internal::StackFrame::ComputeType(v8::internal::StackFrameIteratorBase const*, v8::internal::StackFrame::State*)+0x11f) [0x55df17a474ff]
    ./d8(v8::internal::StackFrameIterator::Advance()+0x36) [0x55df17a46196]
    ./d8(+0x8516fd) [0x55df17a516fd]
    ./d8(v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>)+0x68) [0x55df17a51eb8]
    ./d8(v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection)+0xca) [0x55df17a63bba]
    ./d8(v8::internal::ErrorUtils::MakeGenericError(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode)+0x166) [0x55df17a63e86]
    ./d8(v8::internal::Factory::NewError(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>)+0xa5) [0x55df17a87145]
    ./d8(v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, bool)+0x4e2) [0x55df17b4ea82]
    ./d8(v8::internal::Runtime_LoadNoFeedbackIC_Miss(int, unsigned long*, v8::internal::Isolate*)+0x122) [0x55df17b57922]
    ./d8(+0x114ead9) [0x55df1834ead9]
Received signal 4 ILL_ILLOPN 55df1843ce42
WARN: child terminated by signal: 4: Illegal instruction
```

**Comment by honggyukim** [comment]
```
$ uftrace record  -P. -Z 253 --no-libcall -U Builtins_LoadGlobalIC_NoFeedback ./d8 --expose-gc --trace-gc -e 'gc()'
[154033:0x562725dcd290]       11 ms: Mark-sweep 0.3 (1.6) -> 0.3 (2.6) MB, 0.9 / 0.0 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested

$ uftrace record  -P. -Z 254 --no-libcall ./d8 --expose-gc --trace-gc -e 'gc()'
[154062:0x55cf60ae9e70]       11 ms: Mark-sweep 0.3 (1.6) -> 0.3 (2.6) MB, 0.7 / 0.0 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested

$ uftrace record  -P. -Z 253 --no-libcall ./d8 --expose-gc --trace-gc -e 'gc()'


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffd6c0d7fa0
==== C stack trace ===============================

    /home/honggyu/usr/lib/libmcount.so(backtrace+0x47) [0x7f0ad1653027]
    ./d8(v8::base::debug::StackTrace::StackTrace()+0x13) [0x55fb528ae9d3]
    ./d8(+0x123efcd) [0x55fb528adfcd]
    ./d8(V8_Fatal(char const*, ...)+0x150) [0x55fb528a84f0]
    ./d8(+0x8b495f) [0x55fb51f2395f]
    ./d8(v8::internal::InnerPointerToCodeCache::GetCacheEntry(unsigned long)+0xde) [0x55fb51eb787e]
    ./d8(v8::internal::StackFrame::ComputeType(v8::internal::StackFrameIteratorBase const*, v8::internal::StackFrame::State*)+0x11f) [0x55fb51eb64ff]
    ./d8(v8::internal::StackFrameIterator::Advance()+0x36) [0x55fb51eb5196]
    ./d8(+0x8516fd) [0x55fb51ec06fd]
    ./d8(v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>)+0x68) [0x55fb51ec0eb8]
    ./d8(v8::internal::ErrorUtils::Construct(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>, v8::internal::ErrorUtils::StackTraceCollection)+0xca) [0x55fb51ed2bba]
    ./d8(v8::internal::ErrorUtils::MakeGenericError(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::FrameSkipMode)+0x166) [0x55fb51ed2e86]
    ./d8(v8::internal::Factory::NewError(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>)+0xa5) [0x55fb51ef6145]
    ./d8(v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, bool)+0x4e2) [0x55fb51fbda82]
    ./d8(v8::internal::Runtime_LoadNoFeedbackIC_Miss(int, unsigned long*, v8::internal::Isolate*)+0x122) [0x55fb51fc6922]
    ./d8(+0x114ead9) [0x55fb527bdad9]
Received signal 4 ILL_ILLOPN 55fb528abe42
WARN: child terminated by signal: 4: Illegal instruction
```
The above problem can be fixed by unpatching `Builtins_LoadGlobalIC_NoFeedback`.
```
$ uftrace record  -P. -Z 253 --no-libcall -U Builtins_LoadGlobalIC_NoFeedback ./d8 --expose-gc --trace-gc -e 'gc()'
[154120:0x560fbfa8f290]       11 ms: Mark-sweep 0.3 (1.6) -> 0.3 (2.6) MB, 0.9 / 0.0 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested
```
Here is the disassembly output of the `Builtins_LoadGlobalIC_NoFeedback`.
```asm
00000000010e5600 <Builtins_LoadGlobalIC_NoFeedback>:
 10e5600:       48 8b 7e ff             mov    -0x1(%rsi),%rdi
 10e5604:       4c 8b 41 ff             mov    -0x1(%rcx),%r8
 10e5608:       48 8b 7f 1f             mov    0x1f(%rdi),%rdi
 10e560c:       66 41 83 78 0b 40       cmpw   $0x40,0xb(%r8)
 10e5612:       0f 83 98 00 00 00       jae    10e56b0 <Builtins_LoadGlobalIC_NoFeedback+0xb0>
 10e5618:       4c 8b 87 df 04 00 00    mov    0x4df(%rdi),%r8
 10e561f:       4d 8b 48 07             mov    0x7(%r8),%r9
 10e5623:       49 d1 f9                sar    %r9
 10e5626:       49 83 f9 00             cmp    $0x0,%r9
 10e562a:       0f 86 89 00 00 00       jbe    10e56b9 <Builtins_LoadGlobalIC_NoFeedback+0xb9>
 10e5630:       4d 8b 48 0f             mov    0xf(%r8),%r9
...
```

**Comment by honggyukim** [comment]
But unfortunately, it has more problems. Even if the above functions are unpatched, it still gets segfaulted.
```
$ uftrace record  -P. --no-libcall \
        -U v8::mkdirp \
        -U v8::internal::Accessors::IsJSObjectFieldAccessor \
        -U v8::internal::_GLOBAL__N_1::AsyncGC::RunInternal \
        -U v8::internal::FeedbackNexus::ConfigureHandlerMode \
        -U v8::internal::Parser::ParseOnBackground \
        -U v8::internal::PassesFilter \
        -U v8::internal::wasm::_GLOBAL__N_1::CompileJSToWasmWrapperTask::RunInternal \
        -U v8::internal::TorqueGeneratedClassVerifiers::WasmMemoryObjectVerify \
        -U v8_inspector::V8RuntimeAgentImpl::addBindings \
        -U v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose \
        -U v8::internal::compiler::LoadElimination::AbstractState::KillConstField \
        -U v8::internal::compiler::SimplifiedLowering::LowerAllNodes \
        -U Builtins_LoadGlobalIC_NoFeedback \
        -U icu_65::FormattedStringBuilder::codePointBefore \
        -U icu_65::CanonicalIterator::next \
        -U u_digit_65 \
        -U ures_getByIndex_65 \
        ./d8 --expose-gc --trace-gc -e 'gc()'
Received signal 11 SEGV_ACCERR 7fe80a340058

==== C stack trace ===============================

 [0x7fe80a358027]
 [0x55e60a44e924]
 [0x7fe80a13b390]
 [0x55e609ac387e]
 [0x55e609a5787e]
 [0x55e609a564ff]
 [0x55e609a55196]
 [0x55e609a5ef71]
 [0x55e609abd235]
 [0x55e609aea537]
 [0x55e609ae9e48]
 [0x55e609ab6a0b]
 [0x55e609ab3d02]
 [0x55e609ab1ecf]
 [0x55e609ab337e]
 [0x55e60997db1f]
 [0x55e60997cf9f]
 [0x55e60997c56e]
 [0x55e60a35dbb9]
[end of stack trace]
WARN: child terminated by signal: 11: Segmentation fault
```
This is a reason why I'm afraid of adding more and more techniques on full dynamic tracing. We first have to fix these problems rather than increasing success rate as of now.

**Comment by honggyukim** [comment]
> @honggyukim check that the functions which have 'Builtins_' prefix has recorded. these functions must be exclude from tracing list.

The problem can be fixed by unpatching `Builtins_.*` functions as @ParkHanbum mentioned.
```
$ uftrace record  -P. --no-libcall -U Builtins_.* ./d8 --expose-gc --trace-gc -e 'gc()'
[158184:0x55f62c103a90]       24 ms: Mark-sweep 0.3 (1.6) -> 0.3 (2.6) MB, 2.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested
```
It's because builtin functions are written in assembly and it looks difficult to detect their pattern.

**Comment by honggyukim** [comment]
Here is the full disassembly output. Let's see if it's possible to detect and exclude such functions.
```asm
00000000010e5600 <Builtins_LoadGlobalIC_NoFeedback>:
 10e5600:       48 8b 7e ff             mov    -0x1(%rsi),%rdi
 10e5604:       4c 8b 41 ff             mov    -0x1(%rcx),%r8
 10e5608:       48 8b 7f 1f             mov    0x1f(%rdi),%rdi
 10e560c:       66 41 83 78 0b 40       cmpw   $0x40,0xb(%r8)
 10e5612:       0f 83 98 00 00 00       jae    10e56b0 <Builtins_LoadGlobalIC_NoFeedback+0xb0>
 10e5618:       4c 8b 87 df 04 00 00    mov    0x4df(%rdi),%r8
 10e561f:       4d 8b 48 07             mov    0x7(%r8),%r9
 10e5623:       49 d1 f9                sar    %r9
 10e5626:       49 83 f9 00             cmp    $0x0,%r9
 10e562a:       0f 86 89 00 00 00       jbe    10e56b9 <Builtins_LoadGlobalIC_NoFeedback+0xb9>
 10e5630:       4d 8b 48 0f             mov    0xf(%r8),%r9
 10e5634:       49 d1 f9                sar    %r9
 10e5637:       49 c7 c3 ff ff ff ff    mov    $0xffffffffffffffff,%r11
 10e563e:       49 83 c3 01             add    $0x1,%r11
 10e5642:       4d 3b cb                cmp    %r11,%r9
 10e5645:       7e 69                   jle    10e56b0 <Builtins_LoadGlobalIC_NoFeedback+0xb0>
 10e5647:       4d 8b 60 07             mov    0x7(%r8),%r12
 10e564b:       49 d1 fc                sar    %r12
 10e564e:       4d 8d 73 01             lea    0x1(%r11),%r14
 10e5652:       4d 39 e6                cmp    %r12,%r14
 10e5655:       73 68                   jae    10e56bf <Builtins_LoadGlobalIC_NoFeedback+0xbf>
 10e5657:       4f 8b 64 d8 17          mov    0x17(%r8,%r11,8),%r12
 10e565c:       4d 8b 74 24 0f          mov    0xf(%r12),%r14
 10e5661:       4d 8b 7e 07             mov    0x7(%r14),%r15
 10e5665:       49 d1 ff                sar    %r15
 10e5668:       49 83 ff 00             cmp    $0x0,%r15
 10e566c:       7e d0                   jle    10e563e <Builtins_LoadGlobalIC_NoFeedback+0x3e>
 10e566e:       49 83 ff 02             cmp    $0x2,%r15
 10e5672:       76 4e                   jbe    10e56c2 <Builtins_LoadGlobalIC_NoFeedback+0xc2>
 10e5674:       4d 8b 7e 1f             mov    0x1f(%r14),%r15
 10e5678:       49 d1 ff                sar    %r15
 10e567b:       49 83 c7 03             add    $0x3,%r15
 10e567f:       bb 02 00 00 00          mov    $0x2,%ebx
 10e5684:       48 83 c3 01             add    $0x1,%rbx
 10e5688:       4c 3b fb                cmp    %rbx,%r15
 10e568b:       7e b1                   jle    10e563e <Builtins_LoadGlobalIC_NoFeedback+0x3e>
 10e568d:       49 8b 56 07             mov    0x7(%r14),%rdx
 10e5691:       48 d1 fa                sar    %rdx
 10e5694:       48 3b da                cmp    %rdx,%rbx
 10e5697:       73 2c                   jae    10e56c5 <Builtins_LoadGlobalIC_NoFeedback+0xc5>
 10e5699:       49 39 4c de 0f          cmp    %rcx,0xf(%r14,%rbx,8)
 10e569e:       75 e4                   jne    10e5684 <Builtins_LoadGlobalIC_NoFeedback+0x84>
 10e56a0:       48 8d 7b ff             lea    -0x1(%rbx),%rdi
 10e56a4:       49 8b 44 fc 0f          mov    0xf(%r12,%rdi,8),%rax
 10e56a9:       49 39 45 28             cmp    %rax,0x28(%r13)
 10e56ad:       74 19                   je     10e56c8 <Builtins_LoadGlobalIC_NoFeedback+0xc8>
 10e56af:       c3                      retq
 10e56b0:       48 8b 57 1f             mov    0x1f(%rdi),%rdx
 10e56b4:       e9 e7 00 00 00          jmpq   10e57a0 <Builtins_LoadIC_NoFeedback>
 10e56b9:       cc                      int3
 10e56ba:       e9 71 ff ff ff          jmpq   10e5630 <Builtins_LoadGlobalIC_NoFeedback+0x30>
 10e56bf:       cc                      int3
 10e56c0:       eb 95                   jmp    10e5657 <Builtins_LoadGlobalIC_NoFeedback+0x57>
 10e56c2:       cc                      int3
 10e56c3:       eb af                   jmp    10e5674 <Builtins_LoadGlobalIC_NoFeedback+0x74>
 10e56c5:       cc                      int3
 10e56c6:       eb d1                   jmp    10e5699 <Builtins_LoadGlobalIC_NoFeedback+0x99>
 10e56c8:       55                      push   %rbp
 10e56c9:       48 89 e5                mov    %rsp,%rbp
 10e56cc:       6a 1a                   pushq  $0x1a
 10e56ce:       51                      push   %rcx
 10e56cf:       49 8b 9d a0 25 00 00    mov    0x25a0(%r13),%rbx
 10e56d6:       b8 01 00 00 00          mov    $0x1,%eax
 10e56db:       e8 c0 93 06 00          callq  114eaa0 <Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit>
 10e56e0:       48 8b e5                mov    %rbp,%rsp
 10e56e3:       5d                      pop    %rbp
 10e56e4:       c3                      retq
 10e56e5:       90                      nop
 10e56e6:       66 90                   xchg   %ax,%ax
 10e56e8:       01 00                   add    %eax,(%rax)
 10e56ea:       00 00                   add    %al,(%rax)
 10e56ec:       01 00                   add    %eax,(%rax)
 10e56ee:       00 00                   add    %al,(%rax)
 10e56f0:       e0 00                   loopne 10e56f2 <Builtins_LoadGlobalIC_NoFeedback+0xf2>
 10e56f2:       00 00                   add    %al,(%rax)
 10e56f4:       ff                      (bad)
 10e56f5:       ff                      (bad)
 10e56f6:       ff                      (bad)
 10e56f7:       ff                      (bad)
 10e56f8:       ff                      (bad)
 10e56f9:       ff                      (bad)
 10e56fa:       ff                      (bad)
 10e56fb:       ff 00                   incl   (%rax)
 10e56fd:       cc                      int3
 10e56fe:       cc                      int3
 10e56ff:       cc                      int3
```

**Comment by AnsBal** [comment]
> > @honggyukim check that the functions which have 'Builtins_' prefix has recorded. these functions must be exclude from tracing list.
> 
> The problem can be fixed by unpatching `Builtins_.*` functions as @ParkHanbum mentioned.
> 
> ```
> $ uftrace record  -P. --no-libcall -U Builtins_.* ./d8 --expose-gc --trace-gc -e 'gc()'
> [158184:0x55f62c103a90]       24 ms: Mark-sweep 0.3 (1.6) -> 0.3 (2.6) MB, 2.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) testing GC in old space requested
> ```
> 
> It's because builtin functions are not normal C/C++ functions and it looks difficult to detect their pattern.

I tried to debug one builtin function that crashs ( ``` Builtins_HandleApiCall ```) with gdb and here is what I found:
A series of JUMPS (instead of calls) to other function are performed until the control reaches the following line:

``` 0x55555662b238 <Builtins_AdaptorWithBuiltinExitFrame+24>        mov    %r10,0x20(%rsp) ```

After this point the return address of the frame in not the same anymore. I think it has been overwritten just like  ``` __mcount_entry() ``` does. Few instructions after, a ret instruction is executed and control flow of the program is corrupted.  
To test it in practice, I skipped the line that hijack the return address of the child  in ``` __mcount_entry()  ```and the result was positive.

**Comment by honggyukim** [comment]
@AnsBal Thanks very much for the detail analysis. It might be tricky to handle it.

It doesn't fix this problem for now, but we saw the similar problem in garbage collection phase, but it was resolved by doing auto recover in #418.

FYI, it's merged in the commit below.
- 00340e51 Merge branch 'auto-recover'

**Comment by ParkHanbum** [comment]
@AnsBal actually, that all functions which has Builtins_ prefix are the part of interpreting logic of v8. while interpreting, v8 do so much manipulation to the stack. so, the calling convention is not kept on here. one of them is "On Stack Replamencement" a.k.a OSR optimization. I did some work to keep the safety while interpreting, but it breaked safety in common function. so, I gave up what to support it.

**Comment by honggyukim** [comment]
As you can see from the code below, the builtin function says `"Overwrite the return address on the stack."` at the end of the function.
```cpp
$ cat v8/src/builtins/x64/builtins-x64.cc
    ...
void Builtins::Generate_InterpreterOnStackReplacement(MacroAssembler* masm) {
  {
    FrameScope scope(masm, StackFrame::INTERNAL);
    __ CallRuntime(Runtime::kCompileForOnStackReplacement);
  }

  Label skip;
  // If the code object is null, just return to the caller.
  __ testq(rax, rax);
  __ j(not_equal, &skip, Label::kNear);
  __ ret(0);

  __ bind(&skip);

  // Drop the handler frame that is be sitting on top of the actual
  // JavaScript frame. This is the case then OSR is triggered from bytecode.
  __ leave();

  // Load deoptimization data from the code object.
  __ LoadTaggedPointerField(rbx,
                            FieldOperand(rax, Code::kDeoptimizationDataOffset));

  // Load the OSR entrypoint offset from the deoptimization data.
  __ SmiUntagField(
      rbx, FieldOperand(rbx, FixedArray::OffsetOfElementAt(
                                 DeoptimizationData::kOsrPcOffsetIndex)));

  // Compute the target address = code_obj + header_size + osr_offset
  __ leaq(rax, FieldOperand(rax, rbx, times_1, Code::kHeaderSize));

  // Overwrite the return address on the stack.
  __ movq(StackOperandForReturnAddress(0), rax);

  // And "return" to the OSR entry point of the function.
  __ ret(0);
}
```
https://github.com/v8/v8/blob/dfa569b462c18a08b22009da909d9aeb4a1ae2da/src/builtins/x64/builtins-x64.cc#L2505-L2540

**Comment by honggyukim** [comment]
I'm not sure if it's helpful, but the following commit explains about OnStackReplacement well.
- https://github.com/v8/v8/commit/49d9555a971c5f3cd6982702025765d3abbe92c7
```diff
commit 49d9555a971c5f3cd6982702025765d3abbe92c7
Author:     titzer@chromium.org <titzer@chromium.org@ce2b1a6d-e550-0410-aec6-3dcde31c8c00>
AuthorDate: Mon Sep 9 16:34:40 2013 +0000

    Generate a custom OSR entrypoint for OSR compiles on all platforms, and transition to optimized code using the special entrypoint, instead of through the
deoptimizer. Do not install the OSR compiled code as _the_ optimized code for a function.
    Remove OSR-related stuff from deoptimizer.
    BUG=
    R=mstarzinger@chromium.org

    Review URL: https://codereview.chromium.org/21340002

    git-svn-id: http://v8.googlecode.com/svn/branches/bleeding_edge@16599 ce2b1a6d-e550-0410-aec6-3dcde31c8c00

diff --git a/src/x64/builtins-x64.cc b/src/x64/builtins-x64.cc
--- a/src/x64/builtins-x64.cc
+++ b/src/x64/builtins-x64.cc
@@ -1410,28 +1410,35 @@
 void Builtins::Generate_OnStackReplacement(MacroAssembler* masm) {
   __ movq(rax, Operand(rbp, JavaScriptFrameConstants::kFunctionOffset));

   // Pass the function to optimize as the argument to the on-stack
   // replacement runtime function.
   {
     FrameScope scope(masm, StackFrame::INTERNAL);
     __ push(rax);
     __ CallRuntime(Runtime::kCompileForOnStackReplacement, 1);
   }

-  // If the result was -1 it means that we couldn't optimize the
-  // function. Just return and continue in the unoptimized version.
   Label skip;
-  __ SmiCompare(rax, Smi::FromInt(-1));
+  // If the code object is null, just return to the unoptimized code.
+  __ cmpq(rax, Immediate(0));
   __ j(not_equal, &skip, Label::kNear);
   __ ret(0);

   __ bind(&skip);
-  // Untag the AST id and push it on the stack.
-  __ SmiToInteger32(rax, rax);
-  __ push(rax);
-
-  // Generate the code for doing the frame-to-frame translation using
-  // the deoptimizer infrastructure.
-  Deoptimizer::EntryGenerator generator(masm, Deoptimizer::OSR);
-  generator.Generate();
+
+  // Load deoptimization data from the code object.
+  __ movq(rbx, Operand(rax, Code::kDeoptimizationDataOffset - kHeapObjectTag));
+
+  // Load the OSR entrypoint offset from the deoptimization data.
+  __ SmiToInteger32(rbx, Operand(rbx, FixedArray::OffsetOfElementAt(
+      DeoptimizationInputData::kOsrPcOffsetIndex) - kHeapObjectTag));
+
+  // Compute the target address = code_obj + header_size + osr_offset
+  __ lea(rax, Operand(rax, rbx, times_1, Code::kHeaderSize - kHeapObjectTag));
+
+  // Overwrite the return address on the stack.
+  __ movq(Operand(rsp, 0), rax);
+
+  // And "return" to the OSR entry point of the function.
+  __ ret(0);
 }

```

**Comment by honggyukim** [comment]
It's a bit off topic, but leave some links regarding on stack replacement as a reference (for me).
- [on-stack replacement in v8](https://wingolog.org/archives/2011/06/20/on-stack-replacement-in-v8)
- [CS 7600 Survey Paper: On-Stack Replacement](http://prl.ccs.neu.edu/img/cs7600-mhyee-survey-paper-osr.pdf)

**Comment by ParkHanbum** [comment]
you can found the information associated from here : https://die4taoam.tistory.com/52 (korean)

**Comment by honggyukim** [comment]
@ParkHanbum You've already analyzed it. Thanks for sharing!

**Comment by honggyukim** [comment]
@ParkHanbum Anyway let's back to the problem. Would it be possible to detect such cases to exclude the functions safely?

**Comment by ParkHanbum** [comment]
@honggyukim it cannot be possible until we hijack RET, IMO.

**Comment by AnsBal** [comment]
@honggyukim Thanks for sharing all the resources.
@ParkHanbum I still didn't have time to read about the on-stack replacement technique in details. But I think if we can't support them, we should at least detect them and maybe suggest skipping them to the user. Do you have any idea about how can they be detected ?

**Comment by AnsBal** [comment]
@ParkHanbum If we can be notified when the return address is accessed (Read or Write), we can know where the danger is. And at least let the user know.
We can use hardware breakpoints for this purpose. Since there is a limited number of them in most arch, we can use software watch-points instead (single stepping and checking RET, or a better technique..).

**Comment by ParkHanbum** [comment]
@AnsBal I agree that some technique can mitigate this problem. but if we take it, then it will effect to every other cases. additionally, we do not know how interpreter executed. so, it is only the assuming not the theori. we could not garantee safety of code until we can cover all logic of interpreter.
